project_id = "bzqjxkmkrzvsigimnwwc"

[functions.sync-kevel-inventory]
verify_jwt = false

[functions.push-campaign-to-kevel]
verify_jwt = false

[functions.toggle-campaign-kevel]
verify_jwt = false

[functions.auto-sync-kevel]
verify_jwt = false

[functions.universal-campaign-push]
verify_jwt = false

[functions.log-activity]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.salesforce-oauth-start]
verify_jwt = false

[functions.salesforce-oauth-callback]
verify_jwt = false

[functions.kevel-forecast]
verify_jwt = false

[functions.kevel-forecast-poll]
verify_jwt = false