// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzqjxkmkrzvsigimnwwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cWp4a21rcnp2c2lnaW1ud3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTA1OTEsImV4cCI6MjA2OTQ4NjU5MX0.Qc3ANgy2S4TpnV8FjGTZ0cDw_bI837iIt4fXYqmPxXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});